set history=500
filetype plugin on
filetype indent on
set wildmenu
set hlsearch
set ignorecase
set smartcase
syntax enable
set wrap
set si
set ai
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set number
set cursorline

map <space> /
map <c-space> ?
" Recompile suckless programs
autocmd BufWritePost config.h,config.def.h !sudo make install 
